### ISSUE TITLE
Twitter video gives .m3u8

### ISSUE THREAD

**Issue by NekoAlosama** [qsniyg/maxurl#1005]
Using the Firefox extension, popup keyboard shortcut, and "Link video" on in Popup, I can get the video links to video and gif tweets. Gifs work fine, but videos don't.

In [this tweet](https://twitter.com/wbmc666/status/1495466574408466440), I found that the extension gave me a lower quality video, compared to using https://twittervideodownloader.com/ .
![Screenshot_975](https://user-images.githubusercontent.com/47763383/154876129-3b58afa1-2182-46be-9718-5be6aee9bc9d.png)
![Screenshot_974](https://user-images.githubusercontent.com/47763383/154876134-69930bf3-6e95-41bc-8c79-baaae111d389.png)

In [another tweet](https://twitter.com/weirdrealitymp4/status/1492230083951607817), it seems that the extension gives me a .m3u8 file that seems to supposed to become a .mp4, but doesn't. It's also less than 1 KB. This one at least is the largest that the video downloader above gives.
![Screenshot_976](https://user-images.githubusercontent.com/47763383/154876813-e733049e-9946-4b88-80b6-bdf673c014f7.png)
![Screenshot_977](https://user-images.githubusercontent.com/47763383/154876817-5d257ed1-607e-4d49-a0d0-88c0fe6e08a0.png)

After a second look through the rules, I enabled "Rules using brute-force", but this also gave me a .m3u8. 
![Screenshot_978](https://user-images.githubusercontent.com/47763383/154877252-917c62bc-b48d-4166-a2ac-061225b884a4.png)

Does finding the largest video on Twitter just give you a .m3u8?

**Comment by qsniyg** [comment]
Thanks for reporting! Should be fixed now.

Yes, `.m3u8` will usually return the highest quality. You can download it using youtube-dl/yt-dlp. The way I usually do it is by using Shift+C to copy the URL (unless you bind it to another key), then `yt-dlp '[paste]' -o file.mp4'`. You can disable it if you prefer to have the mp4 file instead. It should now return the highest quality mp4.

**Comment by NekoAlosama** [comment]
Is there an option to manually update the userscript in the extension? It's still not working for me, and I don't know if that's because my extension is outdated or if it just didn't work. I even put my update interval to 1 hour but I've seen nothing,

**Comment by qsniyg** [comment]
I haven't updated the extension on AMO yet. You can sideload the addon though, instructions are in the README :)

**Comment by NekoAlosama** [comment]
While trying the XPI method, I saw that the .xpi is outdated, since it's the 0.19.4 version.

**Comment by NekoAlosama** [comment]
@qsniyg When will you update the extension on AMO?
