### ISSUE TITLE
Only showing small pictures on imagefap.com

### ISSUE THREAD

**Issue by CupaButton** [qsniyg/maxurl#370]
Used to be able to click next and get a big picture on imagefap.com, not anymore. Just get the thumb.

**Comment by qsniyg** [comment]
Could you send an example of an image/page that doesn't work? It still seems to work fine for me... maybe it's a regional update or something?

**Comment by CupaButton** [comment]
After getting a big picture, moving to the right (next in gallery) I get a small picture. See picture below. Used to get a big picture when I did this.
![image](https://user-images.githubusercontent.com/67788703/86494173-8563fd00-bd74-11ea-877a-3e6ff5d743ad.png)

**Comment by qsniyg** [comment]
Sorry, again, I'm unable to reproduce this, it works fine on my end... could you right click on the image in the popup, then select "copy link address" and paste it here? Also, would you mind sending a link to the gallery with the issue (just in case the galleries I've tried for some reason don't exhibit the same issue).

**Comment by CupaButton** [comment]
Copied link address from popup.
https://www.imagefap.com/photo/554287501/?pgid=&gid=8240211&page=0&idx=5#
Gallary:
https://www.imagefap.com/pictures/8240211/Alexandra-Shapovalova

**Comment by CupaButton** [comment]
I deleted the script, and reinstalled it. Works now.

**Comment by qsniyg** [comment]
Huh weird... well I'm glad to know it works now :) I'll close the issue then, but if you encounter it again, please let me know!

**Comment by CupaButton** [comment]
Having exactly the same problem again. Reinstalled the script. Did not help. Works everywhere else just fine. Also deleted all cockies and data in browser. Using Opera.

**Comment by qsniyg** [comment]
Yeah they changed it a few days ago, fixed here: https://github.com/qsniyg/maxurl/commit/75d7cfe4a7d008e72f30da0a0f2b8bea68207b16

Try using the latest git version, it should work :)

**Comment by CupaButton** [comment]
Great stuff. Works again. Thanks for the update!

**Comment by CupaButton** [comment]
I have this problem again. Happens on the extension and the script.

**Comment by qsniyg** [comment]
Thanks for reporting, should be fixed!

**Comment by CupaButton** [comment]
Still does not work for me. Using Opera. Deleted the extension. Downloaded and installed the new master. Cleared cash. Still same result. Same result on the script as well :/

**Comment by qsniyg** [comment]
Interesting, it works for me... are you using the latest git version? If so, what's the URL of the image?

**Comment by CupaButton** [comment]
Your response made me revisit how I updated my extensions from Git. I had forgotten that I needed to us the load function. It's all good. It works as you say. Sorry for my late reply and thank you for your good work.
